name: Test

on: [push]


jobs:
  job_1:
    runs-on: ubuntu-latest
    container: pvitello/computational-workflows:latest
    steps:
      - name: My first step
        uses: actions/checkout@v2
      - name: Run step
        run:  py.test-3
        


